#image: amazoncorreto

#stages:
#  - compile
#  - test

#compile:
#  stage: compile
#  artifacts:
#    untracked: true
#  script:
#   - javac *.java

#test:
#  stage: test
#  script:
#    - java FunctionsTest


image: maven:3.6.3-jdk-11

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
